Message Count Rewards
DZ-TM/Yagpdb.xyz pull request #4
Opened 2020-11-15 02:39 UTC by NaruDevnote

Simple rewards checker for each count goal that is reached, starting at 50. Everything is commented and readily editable.

2020-11-15 12:16 UTC, DZ-TM commented
Seems perfect but it should be put under the already made message count cmd (in the code, at the bottom) cus it uses .* regex already so two .* regex is a waste

2020-11-15 20:38 UTC, Jo3-L requested changes
smh forgetting about the poor comments

2020-11-15 20:38 UTC, Jo3-L commented on Commands/MessageCount/countRewards.go
> +    {{/* Ranges the KEY:VALUE pairs of the rewards */}}
```suggestion
    {{- /* Ranges the KEY:VALUE pairs of the rewards */}}
```
comment blocks need to be stripped too

2020-11-15 20:38 UTC, Jo3-L commented on Commands/MessageCount/countRewards.go
> +        {{/* Checks if the user has a message count >= each KEY of the rewards AND that they do not already have that role reward */}}
```suggestion
        {{- /* Checks if the user has a message count >= each KEY of the rewards AND that they do not already have that role reward */}}
```
ditto

2020-11-15 20:38 UTC, Jo3-L commented on Commands/MessageCount/countRewards.go
> +            {{/* Adds the role(s) corresponding to the VALUE of the rewards if true */}}
```suggestion
            {{- /* Adds the role(s) corresponding to the VALUE of the rewards if true */}}
```

2020-11-15 20:38 UTC, Jo3-L commented on Commands/MessageCount/countRewards.go
> +			      {{/* Sends the congrats message */}}
```suggestion
			      {{- /* Sends the congrats message */}}
```

2020-11-15 20:38 UTC, Jo3-L commented on Commands/MessageCount/countRewards.go
> +    {{- end}}
```suggestion
    {{ end}}
```
theres no need for this

2020-11-16 02:03 UTC, soudblox commented
damn looks lit, can i use it now xd

2020-11-22 12:54 UTC, closed without merging